const modCalc = require('./moduloCalculo')
const modValores = require('./constantes')
const _ = require('lodash')

console.log(">>> Iniciando testes com módulos.")
console.log(" ")
console.log("modCalc = " + modCalc)
console.log("modValores = " + modValores)
console.log(" ")
console.log(modCalc.Valor1)
console.log("## Soma ## ")
console.log(`A soma de ${modValores.Valor1} e ${modValores.Valor2} é: ${modCalc.Soma(modValores.Valor1,modValores.Valor2)}`)
console.log(" ")
console.log("## Subtração ## ")
console.log(`A diferença de ${modValores.Valor1} e ${modValores.Valor2} é: ${modCalc.Subtrai(modValores.Valor1,modValores.Valor2)}`)
console.log(" ")

//console.log("## Multiplicação ## ")
var valor1 = modValores.Valor1
var valor3 = modValores.Valor3()
console.log("Valor 1 = " + valor1)
console.log(`A multiplicacao de ${valor3} * 5 é: ${modCalc.Multiplica(valor3,5)}`)